// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP_API_Udemy_Course.Migrations
{
    [DbContext(typeof(Hotel_Listing_DB_Context))]
    partial class Hotel_Listing_DB_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP_API_Udemy_Course.data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id") , 1 , 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "egypt",
                            ShortName = "EG"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Saudia arabia",
                            ShortName = "SAR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "United Arab Imarates",
                            ShortName = "UAE"
                        });
                });

            modelBuilder.Entity("ASP_API_Udemy_Course.data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1 , 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "MAKA",
                            CountryId = 2,
                            Name = "the clock tower",
                            Rating = 5
                        },
                        new
                        {
                            Id = 2,
                            Address = "Dubai",
                            CountryId = 3,
                            Name = "Burj Khalifa",
                            Rating = 5
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alexandrai",
                            CountryId = 1,
                            Name = "The Four Seasoons",
                            Rating = 4
                        },
                        new
                        {
                            Id = 4,
                            Address = "Almadina Almonawara",
                            CountryId = 2,
                            Name = "Almadina Hotel",
                            Rating = 5
                        });
                });

            modelBuilder.Entity("ASP_API_Udemy_Course.data.Hotel", b =>
                {
                    b.HasOne("ASP_API_Udemy_Course.data.Country", "country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("country");
                });

            modelBuilder.Entity("ASP_API_Udemy_Course.data.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
